# Generated by Django 4.1.7 on 2023-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='patient_profiles/')),
            ],
        ),
    ]
