# Generated by Django 4.1.7 on 2023-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0006_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnologist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='lab_technologist_profiles/')),
            ],
        ),
    ]
