# Generated by Django 4.1.7 on 2023-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.BigIntegerField(default=9000)),
                ('Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=300)),
                ('joined_date', models.DateField()),
                ('Email_id', models.CharField(max_length=100)),
                ('Contact_no', models.CharField(max_length=100)),
                ('No', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.BigIntegerField()),
                ('Email_id', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EmployeeAuth',
            },
        ),
    ]
