# Generated by Django 4.1.7 on 2023-05-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Care_Employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeAuth',
        ),
    ]
