# Generated by Django 4.1.7 on 2023-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patients_delete_documents_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
