# Generated by Django 4.1.7 on 2023-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0005_delete_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('MobileNumber', models.CharField(max_length=10)),
                ('EmailId', models.CharField(max_length=100)),
                ('CareTakerName', models.CharField(max_length=100)),
                ('CareTakerMobileNumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=500)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
    ]
