# Generated by Django 4.1.7 on 2023-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Patient_Id',
            field=models.BigIntegerField(default=1000),
        ),
    ]
