# Generated by Django 4.1.7 on 2023-03-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_patients_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
