# Generated by Django 4.1.7 on 2023-03-26 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
