# Generated by Django 4.1.7 on 2023-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_patients_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_photo',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
