# Generated by Django 4.1.7 on 2023-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_patients_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatmentplan',
            fields=[
                ('patient_id', models.BigIntegerField(db_column='Patient_Id', primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=50, null=True)),
            ],
            options={
                'db_table': 'treatmentplan',
                'managed': False,
            },
        ),
    ]
