# Generated by Django 4.1.7 on 2023-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatmentplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=50, null=True)),
            ],
            options={
                'db_table': 'treatmentplan',
                'managed': False,
            },
        ),
    ]
