# Generated by Django 4.1.7 on 2023-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_treatmentplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treatmentplan',
        ),
    ]
